/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.2.9-106-g1076d31485"
#endif /* AVUTIL_FFVERSION_H */
